name: dadata_suggestions
description: Dadata address suggestions (including forward and reverse geocoding) for Flutter.
version: 0.1.2
repository: https://github.com/illabo/dadata_suggestions

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

flutter:
